# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZZbJtS36o-g3anY18j5QGbGXlhW52_tz
"""

#pip install streamlit pandas matplotlib plotly
#pip install data_sources

import os
import joblib
import numpy as np
import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
import requests

# Set the title of the app
st.title("Real-Time Weather Data")

# User input for city
city = st.text_input("Enter city name", "Toronto")

# OpenWeatherMap API key and URL
api_key = "0daa089ec817d4921f4a1df8478dc369"
url = f"https://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}"

# Function to fetch weather data
def fetch_weather_data(city):
    response = requests.get(url.format(city=city))

    if response.status_code == 200:
        data = response.json()

        city_name = data['name']
        weather_description = data['weather'][0]['description']
        temperature = data['main']['temp'] - 273.15  # Convert from Kelvin to Celsius
        pressure = data['main']['pressure']
        humidity = data['main']['humidity']
        wind_speed = data['wind']['speed']

        return {
            'city': city_name,
            'description': weather_description,
            'temperature': temperature,
            'pressure': pressure,
            'humidity': humidity,
            'wind_speed': wind_speed
        }
    else:
        return None

# Fetch weather data when the city is entered
if city:
    weather_data = fetch_weather_data(city)

    if weather_data:
        st.subheader(f"Weather in {weather_data['city']}:")
        st.write(f"Description: {weather_data['description']}")
        st.write(f"Temperature: {weather_data['temperature']:.2f}°C")
        st.write(f"Pressure: {weather_data['pressure']} hPa")
        st.write(f"Humidity: {weather_data['humidity']}%")
        st.write(f"Wind Speed: {weather_data['wind_speed']} m/s")
    else:
        st.error("Failed to retrieve data from OpenWeatherMap API. Please try again.")

#!ls  # Check if the file exists in the current directory
